### ISSUE TITLE
【todo】Check_box for Features

### ISSUE THREAD

**Issue by lyleshaw** [wechaty/python-wechaty-puppet-itchat#9]
- [x] handle Map,Card,Note,Sharing,Picture,Recording,Attachment,Video messages
- [x] handle Friends,System messages
- [x] Encapsulate message_send_contact function (itchat doesn't exist this function)
- [x] Encapsulate message_send_url function (itchat doesn't exist this function)
- [x] Encapsulate message_send_mini_program function (itchat doesn't exist this function)
- [x] Encapsulate message_file function
- [x] Encapsulate message_emoticon function
- [x] Encapsulate message_contact function
- [x] Encapsulate message_url function
- [x] Encapsulate message_mini_program function (itchat doesn't exist this function)
- [x] Encapsulate contact_alias function
- [x] Encapsulate contact_payload function
- [x] Encapsulate contact_avatar function
- [x] Encapsulate contact_tag_ids function (itchat doesn't exist this function)
- [x] Encapsulate friendship_search function
- [x] Encapsulate friendship_add function
- [x] Encapsulate friendship_accept function
- [x] Encapsulate room_create function
- [x] Encapsulate room_search function
- [x] Encapsulate room_invitation_accept function (itchat doesn't exist this function)
- [x] Encapsulate room_members function
- [ ] Encapsulate room_add function
- [ ] Encapsulate room_delete function
- [x] Encapsulate room_quit function (itchat doesn't exist this function)
- [ ] Encapsulate room_topic function
- [x] Encapsulate room_announce function (itchat doesn't exist this function)
- [x] Encapsulate room_qr_code function (itchat doesn't exist this function)
- [x] Encapsulate room_avatar function
